import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  titleText: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#5B5B5B",
    marginBottom: 7,
  },
  paragraph: {
    marginVertical: 8,
    lineHeight: 20,
  },
  container: {
    backgroundColor: "#222",
    flex: 1,
  },
  containerCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  gameTitleLogin: {
    // flex: 1,
    fontSize: 40,
    fontWeight: "bold",
    color: "#5B5B5B",
    marginTop: 70,
    marginBottom: -125,
  },
  gameTitleLevels: {
    flex: 1,
    fontSize: 40,
    fontWeight: "bold",
    color: "#5B5B5B",
    marginTop: 70,
    marginBottom: -125,
  },
  textInput: {
    color: "#222",
    backgroundColor: "#C4C4C4",
    fontSize: 16,
    height: 30,
    width: 250,
    borderWidth: 1,
    borderColor: "grey",
    borderRadius: 15,
    marginBottom: 7,
    paddingLeft: 15,
  },
  levelSelector: {
    color: "#C4C4C4",
    textAlign: "center",
    fontWeight: "bold",
    backgroundColor: "#333",
    fontSize: 16,
    height: 30,
    width: 40,
    borderWidth: 1,
    borderColor: "#C4C4C4",
    borderRadius: 15,
    margin: 7,
    padding: 5,
  },
  levelImage: {
    height: 30,
    width: 30,
  },
  button: {
    color: "#C4C4C4",
    textAlign: "center",
    fontWeight: "bold",
    backgroundColor: "#333",
    fontSize: 16,
    height: 30,
    width: 100,
    borderWidth: 1,
    borderColor: "#C4C4C4",
    borderRadius: 15,
    marginTop: 7,
    padding: 5,
  },
  levelScroll: {
    // height: 50,
    width: "100vw",
    maxWidth: 350,
    paddingLeft: 50,
    paddingRight: 50,
  },
  levelScroll1: {
    alignContent: "center",
  },
  gameHUD: {
    margin: 30,
    color: "#5B5B5B",
  },
  gameHudLevel: {
    // flex: 1,
    textAlign: "center",
    fontSize: 25,
    fontWeight: "bold",
    color: "#5B5B5B",
  },
  playerLevelDisplay: {
    // flex: 1,
    flexDirection: "row",
  },
  playerLevelDisplayText: {
    // flex: 1,
    fontSize: 25,
    fontWeight: "bold",
    color: "#5B5B5B",
  },
  playerLevelDisplayBarOuter: {
    // flex: 1,
    width: 150,
    height: 20,
    backgroundColor: "#333",
    borderWidth: 1,
    borderColor: "#C4C4C4",
    borderRadius: 10,
    marginLeft: 5,
    marginTop: 5,
  },
  playerLevelDisplayBarInner: {
    // flex: 1,
    // width: 100,
    height: 18,
    backgroundColor: "#818181",
    borderRadius: 10,
  },
  playerHpDisplay: {
    // flex: 1,
    flexDirection: "row",
  },
  playerHpDisplayText: {
    // flex: 1,
    fontSize: 25,
    fontWeight: "bold",
    color: "#5B5B5B",
  },
  playerHpDisplayBarOuter: {
    // flex: 1,
    width: 150,
    height: 20,
    backgroundColor: "#333",
    borderWidth: 1,
    borderColor: "#C4C4C4",
    borderRadius: 10,
    marginLeft: 5,
    marginTop: 5,
  },
  playerHpDisplayBarInner: {
    // flex: 1,
    // width: 100,
    height: 18,
    backgroundColor: "#8B0000",
    borderRadius: 10,
  },
  shieldDisplay: {
    // flex: 1,
    flexDirection: "row",
  },
  shieldDisplayText: {
    // flex: 1,
    fontSize: 25,
    fontWeight: "bold",
    color: "#5B5B5B",
  },
  shieldDisplayBarOuter: {
    // flex: 1,
    width: 150,
    height: 20,
    backgroundColor: "#333",
    borderWidth: 1,
    borderColor: "#C4C4C4",
    borderRadius: 10,
    marginLeft: 5,
    marginTop: 5,
  },
  shieldDisplayBarInner: {
    // flex: 1,
    // width: 100,
    height: 18,
    borderRadius: 10,
  },
  weaponDisplay: {
    // flex: 1,
    flexDirection: "row",
  },
  weaponDisplayText: {
    // flex: 1,
    fontSize: 25,
    fontWeight: "bold",
    color: "#5B5B5B",
  },
  weaponDisplayBarOuter: {
    // flex: 1,
    width: 150,
    height: 20,
    backgroundColor: "#333",
    borderWidth: 1,
    borderColor: "#C4C4C4",
    borderRadius: 10,
    marginLeft: 5,
    marginTop: 5,
  },
  weaponDisplayBarInner: {
    // flex: 1,
    // width: 100,
    height: 18,
    borderRadius: 10,
  },
});
